extends: '@absolunet/jsdoc'


# Parser Options
parserOptions:
  sourceType: module


# Rules
rules:

  # Best Practices
  no-warning-comments: [warn, { location: anywhere }]


  # 🦄 Unicorn
  unicorn/expiring-todo-comments: [error, { allowWarningComments: false }]
