extends:
  - '@absolunet/node'
  - '@absolunet/package'


# Plugins
plugins:
  - import


# Rules
rules:

  # Node - Possible Errors
  node/no-extraneous-import: [error]
  node/no-missing-import: [error]
  node/no-unpublished-import: [error]


  # Node - Stylistic Issues
  node/file-extension-in-import: [error, always]


  # 🦄 Unicorn
  unicorn/prefer-module: [error]
  unicorn/prefer-node-protocol: [error]


  # Import - Static analysis
  import/no-unresolved: [error]
  import/named: [error]
  import/default: [error]
  import/namespace: [error]
  import/no-restricted-paths: [off]
  import/no-absolute-path: [error]
  import/no-dynamic-require: [error]
  import/no-internal-modules: [off]
  import/no-webpack-loader-syntax: [error]
  import/no-self-import: [error]
  import/no-cycle: [error]
  import/no-useless-path-segments: [error]
  import/no-relative-parent-imports: [off]
  import/no-relative-packages: [error]


  # Import - Helpful warnings
  import/export: [error]
  import/no-named-as-default: [error]
  import/no-named-as-default-member: [error]
  import/no-deprecated: [error]
  import/no-extraneous-dependencies: [error]
  import/no-mutable-exports: [error]
  import/no-unused-modules: [error]


  # Import - Module systems
  import/unambiguous: [error]
  import/no-commonjs: [error]
  import/no-amd: [error]
  import/no-nodejs-modules: [off]
  import/no-import-module-exports: [error]


  # Import - Style guide
  import/first: [error]
  import/exports-last: [error]
  import/no-duplicates: [error]
  import/no-namespace: [error]
  import/extensions: [error, always]
  import/order:
    - error
    - groups:
        - builtin
        - external
        - internal
        - parent
        - sibling
        - index
        - object
        - type
      alphabetize:
        order: asc
        caseInsensitive: true

  import/newline-after-import: [error]
  import/prefer-default-export: [error]
  import/max-dependencies: [off]
  import/no-unassigned-import: [error]
  import/no-named-default: [error]
  import/no-default-export: [off]
  import/no-named-export: [off]
  import/no-anonymous-default-export: [error]
  import/group-exports: [error]
  import/dynamic-import-chunkname: [off]
