extends: '@absolunet/core'

# Environments
env:
  browser: true
  jquery: true


# Rules
rules:

  # Strict Mode
  strict: [error, function]

  # IE11 incompatibility
  require-unicode-regexp: [off]




  # 🦄 Unicorn
  unicorn/prefer-add-event-listener: [error]
  unicorn/prefer-node-append: [error]
  unicorn/prefer-node-remove: [error]
  unicorn/prefer-query-selector: [error]
  unicorn/prefer-text-content: [error]
