extends: "@absolunet/core"

# Environments
env:
  node: true


# Rules
rules:

  # Strict Mode
  strict: [error, global]

  # Node.js and CommonJS
  callback-return: [error]
  global-require: [error]
  handle-callback-err: [error]
  no-buffer-constructor: [error]
  no-mixed-requires: [error]
  no-new-require: [error]
  no-path-concat: [error]
  no-process-env: [error]
  no-process-exit: [error]
  no-restricted-modules: [off]
  no-restricted-properties: [off]
  no-sync: [off]


  # ECMAScript 6
  no-restricted-imports:
    - error
    - assert
    - buffer
    - child_process
    - cluster
    - crypto
    - dgram
    - dns
    - domain
    - events
    - freelist
    - fs
    - http
    - https
    - module
    - net
    - os
    - path
    - punycode
    - querystring
    - readline
    - repl
    - smalloc
    - stream
    - string_decoder
    - sys
    - timers
    - tls
    - tracing
    - tty
    - url
    - util
    - vm
    - zlib
