extends:
  - "@absolunet/eslint-config-core"
  - "plugin:node/recommended-module"
  - "plugin:import/recommended"
  - "plugin:import/typescript"

settings:
  import/resolver:
    typescript:
      alwaysTryTypes: true

rules:
  node/no-missing-import: [off]
  import/extensions: [off]
