extends: '@absolunet/core'

# Environments
env:
  browser: true
  jquery: true


# Globals
globals:
  global: false

  # nwayo
  konstan: false
  app: false
  __: false
  PROJECT: false
  DOM_PARSED: false
  DOCUMENT_LOADED: false
  GLOBAL_JQUERY_LOADED: false

  # nwayo vendors
  _: false
  Modernizr: false
  pinki: false

  # Classic libs
  addthis: false
  addthis_config: true
  addthis_share: true
  Cookies: false
  FastClick: false
  Foundation: false
  google: false
  kafe: false
  toolbox: false
  WebFont: false


# Rules
rules:

  # Strict Mode
  strict: [error, function]

  # IE11 incompatibility
  require-unicode-regexp: [off]




  # 🦄 Unicorn
  unicorn/prefer-add-event-listener: [error]
