extends: '@absolunet/browser'

# Globals
globals:
  global: readonly

  # nwayo
  konstan: readonly
  app: readonly
  __: readonly
  PROJECT: readonly
  DOM_PARSED: readonly
  DOCUMENT_LOADED: readonly
  GLOBAL_JQUERY_LOADED: readonly

  # nwayo vendors
  _: readonly
  Modernizr: readonly
  pinki: readonly

  # Classic libs
  addthis: readonly
  addthis_config: writable
  addthis_share: writable
  Cookies: readonly
  FastClick: readonly
  Foundation: readonly
  google: readonly
  kafe: readonly
  toolbox: readonly
  WebFont: readonly
