plugins:
# - import       (from airbnb)
# - jsx-a11y     (from airbnb)
  - ordered-imports
# - react        (from airbnb)
# - react-hooks  (from airbnb)

extends:
  - 'airbnb'
  - 'airbnb/hooks'
  - 'eslint:recommended'
  - '@absolunet/browser'


# Parser Options
parser: '@babel/eslint-parser'
parserOptions:
  sourceType: module


# Rules
rules:

  # Variables
  no-restricted-globals: [off]


  # 🦄 Unicorn
  unicorn/prevent-abbreviations: [error, { checkProperties: true, checkFilenames: false, replacements: { props: false } }]


  # React
  react/no-danger: [error]


  # React - JSX-specific rules
  react/jsx-filename-extension: [error, { extensions: ['.js', '.jsx'] }]
