extends:
  - 'airbnb'
  - '@absolunet/browser'

parser: babel-eslint

parserOptions:
  sourceType: module

globals:
  pinki: readonly

rules:

  no-restricted-globals: [off]

  unicorn/prevent-abbreviations: [error, { replacements: { props: false } }]

  import/prefer-default-export: [off]

  react/jsx-filename-extension: [error, { extensions: ['.js'] }]
  react/jsx-indent: [error, 'tab']
  react/jsx-indent-props: [error, 'tab']
